### ISSUE TITLE
安装下来运行，报错了~

### ISSUE THREAD

**Issue by demigodliu** [itsuki0927/SkCode#1]
请问下大佬，这个问题该怎么解决？
```js
Error executing vim.schedule lua callback: vim/_meta.lua:324: Invalid option type 'nil' for 'shada
file', should be string or table
stack traceback:
        [C]: in function 'error'
        vim/_meta.lua:324: in function 'assert_valid_value'
        vim/_meta.lua:393: in function 'convert_value_to_vim'
        vim/_meta.lua:681: in function '_set'
        vim/_meta.lua:724: in function '__newindex'
        /Users/demigodliu/.config/nvim/lua/core/options.lua:76: in function </Users/demigodliu/.co
nfig/nvim/lua/core/options.lua:75>
```

**Comment by itsuki0927** [comment]
你的neovim版本是多少呀?

**Comment by demigodliu** [comment]
> 

NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
编译者 brew@HMBRW-A-001-M1-002.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/opt/homebrew/Cellar/neovim/0.6.0/share/nvim"

Run :checkhealth for more info

**Comment by itsuki0927** [comment]
我刚修复了, 你pull一下试试

**Comment by demigodliu** [comment]
这次没报错了，麻烦大佬再看看在，和谐内容，是需要一个一个安装更新吗？
![](https://s3.bmp.ovh/imgs/2022/03/9332ee2e83d25ff8.png)

**Comment by demigodliu** [comment]
请问这些包没找到，是需要自己安装吗？
![](https://s3.bmp.ovh/imgs/2022/03/a7457ba228003514.png)

**Comment by itsuki0927** [comment]
你运行了`PackerSync`命令吗?

**Comment by demigodliu** [comment]
我是在 nvim 目录下运行的：`nvim +PackerSync`
然后，就报错如上图所示。

**Comment by demigodliu** [comment]
我试了一下，运行 `nvim :PackerSync` 效果也是和上面的报错一样

**Comment by itsuki0927** [comment]
好, 稍等, 我排查一下

**Comment by demigodliu** [comment]
万分感谢！！

**Comment by itsuki0927** [comment]
我这边看了下, windows和mac都没有问题, 你可以看看, 你的bufferline有没有安装上, 我感觉是你的插件安装到了一个错误的地方.
你可以看看`plugin/packer_compiled.lua`文件是不是正确的路径.
![WechatIMG2277](https://user-images.githubusercontent.com/40518195/158131373-84348552-01a4-4d43-853e-c266befb16db.jpeg)

**Comment by demigodliu** [comment]
好的，我先自查一下，感谢

**Comment by itsuki0927** [comment]
你如果没有解决的话, 我晚上给你远程看看, 可以🤔

**Comment by demigodliu** [comment]
可以~

**Comment by itsuki0927** [comment]
解决了吗?

**Comment by demigodliu** [comment]
> 

还没有，昨天没弄，忙着工作，空余时间还是没弄出来，第一次使用 vim，安装插件都不知道怎么安装，正准备晚上空了看看教程

**Comment by itsuki0927** [comment]
我也是这两天有点忙, 没弄好的话, 周末给你弄一下, 安装插件、Lsp这个我在文档中有写, 你可以去看看

**Comment by demigodliu** [comment]
> 我也是这两天有点忙, 没弄好的话, 周末给你弄一下, 安装插件、Lsp这个我在文档中有写, 你可以去看看

好的，我周末的时候弄一下，感谢🙏

**Comment by itsuki0927** [comment]
你啥时候有时间呢?

**Comment by demigodliu** [comment]
> 你啥时候有时间呢?

已经弄好了，大佬～

**Comment by itsuki0927** [comment]
可以, 怎么解决的?

**Comment by demigodliu** [comment]
> 可以, 怎么解决的?

看了看neovim的课程
