### ISSUE TITLE
treesitter 报错

### ISSUE THREAD

**Issue by cworld1** [itsuki0927/SkCode#12]
我还特地确认了下库，应该是没有问题的。

![uTools_1667184725056](https://user-images.githubusercontent.com/37377181/198921314-e1b6d75b-cdec-41d9-8547-51f311f31251.png)

packersync 也是正常的。
![uTools_1667184760984](https://user-images.githubusercontent.com/37377181/198921383-30b7bc51-38db-4ee0-93b3-1983b4201cd4.png)

唯独不正常的是大量报错。lsp已经全数禁用。确实不太熟悉treesitter。看了下配置文件，还不太方便简单禁用掉插件...虽然最后决定把plugin配置的setup注释掉解决了。系统耦合度太高也许并不是一件好事。？
![uTools_1667184786680](https://user-images.githubusercontent.com/37377181/198921470-f1cef99e-8f82-45c2-b153-3d5b61692163.png)

**Comment by itsuki0927** [comment]
因为默认就是全部安装，所以会出现这个问题，目前改成了安装常用的语言，如果有需要自己安装就好。

耦合度太高，可能是readme的问题导致这个仓库是一个ide，其实只是我自己的个人nvim配置，所以我比较随心所欲~
