### ISSUE TITLE
請問關於一些亂碼的問題

### ISSUE THREAD

**Issue by changchichung** [itsuki0927/SkCode#14]
在你的網站中有這麼一張圖片

![](https://p1-tt.byteimg.com/origin/tos-cn-i-qvj2lq49k0/c7501a559acc40e7b5adb06126ef28b1.jpg)

可以看到每個選項前面的 icon 都有出現

可是我的長這樣

![](https://i.imgur.com/knLcsb2.png)

前面的icon 像是亂碼，這是我有少裝了什麼東西或字體嗎？

**Comment by itsuki0927** [comment]
是的，需要安装带图标的字体，可以在这里找到你想要的[字体](https://github.com/ryanoasis/nerd-fonts)下载安装就可以了。
