### ISSUE TITLE
lsp报错

### ISSUE THREAD

**Issue by louis2610** [itsuki0927/SkCode#15]
我按你的文档，通过yarn全局安装了lsp，还是报错
![image](https://user-images.githubusercontent.com/4217225/229986833-3aa92bf8-a74c-4c7a-bacf-a99f8ea63ec3.png)

**Comment by so1ve** [comment]
你确定yarn全局安装目录在你的path里头吗

**Comment by zerrol** [comment]
用 yarn 不行，因为 yarn 不会创建全局环境变量，需要用 npm
`npm install -g xxx-xxx-server`

**Comment by so1ve** [comment]
@zerrol 那就是你环境变量没配好
