### ISSUE TITLE
E15: Invalid expression: v:lua.require('ui.statusline').run()

### ISSUE THREAD

**Issue by bigboysuper6** [itsuki0927/SkCode#17]
报错E15: Invalid expression: v:lua.require('ui.statusline').run()，google后找到相关的[issue](https://github.com/NvChad/NvChad/issues/1265) ，nvChad似乎解决了这个问题，但在SkCode中依旧会出现。
bug发生的时间：在第一次从nvim-tree中打开js文件时出现
系统：win11
截图：
![屏幕截图 2023-08-06 162818](https://github.com/itsuki0927/SkCode/assets/66550929/eb480d95-0745-4d25-99c0-18ed44c18655)

**Comment by matu3ba** [comment]
fix is likely something along `vim.o.statusline = "%!v:lua.require'my_statusline'.setup()"`
