### ISSUE TITLE
close_buffer 采用 :bd<CR> 在某些情况下 会退出 neovim 

### ISSUE THREAD

**Issue by nshusr** [itsuki0927/SkCode#2]
我看到 nvchad 已修改 close_buffer 的方法

https://github.com/NvChad/NvChad/blob/76d194b1414d2351364ef1a84672e6b95110b65a/lua/core/utils.lua#L4-L117

不知道大家有没有谁遇到过现在所使用的 `:bd<CR>` 这种 `<leader>x` 会退出程序的情况

**Comment by itsuki0927** [comment]
别说, 我还真碰到这样子的情况, 哈哈哈哈 ,我晚点去看看它的这个`close_buffer`代码.

**Comment by itsuki0927** [comment]
我在本地测试了下, 发现使用`:bd<CR>`会退出程序的场景是`nvim-tree`是打开的状态, 然后在通过`<leader>x`关闭buffer(打开两个以上的buffer)时, 会直接退出nvim.
