### ISSUE TITLE
ToggleTerm 载入不成功

### ISSUE THREAD

**Issue by nshusr** [itsuki0927/SkCode#3]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/45023042/159295945-9dd91843-dbd1-4ba1-a51b-0245915e38e6.png">

```  lua
 _LAZYGIT_TOGGLE()
 _RANGER_TOGGLE() 
```
这两个方法未找到

**Comment by itsuki0927** [comment]
1. 目前这个`toggleterm`还有一些问题, 原因是`toggleterm`采用了懒加载, 只有按下`ctrl + \`这两个键才会加载`toggleterm`, 所以直接调用`<leader>tg`是不会加载`toggleterm`的, 这个体验挺难受的, 我自己也受不了这个流程.
2. 我发现在`toggleterm`在使用`lazygit`中, `lazygit`的键位不起作用,  所以我目前都是先退出nvim, 然后在命令行使用`lazygit`操作.
感谢你的建议, 我晚一点修复一下!

**Comment by itsuki0927** [comment]
我找了下`toggleterm`的issue, 没找到相关的解决办法, 只能先使用[vim-floaterm](https://github.com/voldikss/vim-floaterm)这个库, 一样可以实现这个功能, 而且还能完美解决打开浮窗不能使用相关的快捷键的问题.

<img width="1680" alt="Screen Shot 2022-04-02 at 5 47 23 PM" src="https://user-images.githubusercontent.com/40518195/161377660-9c523d71-7e59-4aa3-ab2d-732d1b4c9648.png">
<img width="1680" alt="Screen Shot 2022-04-02 at 5 47 36 PM" src="https://user-images.githubusercontent.com/40518195/161377664-71921a22-2403-40d7-a7f8-b00ccbf2457a.png">

**Comment by itsuki0927** [comment]
c3f3e6868f8228a26f1d5693b6f32d9a743fa873 已修复
