### ISSUE TITLE
有么有办法能离线安装？

### ISSUE THREAD

**Issue by DeruiLiu** [itsuki0927/SkCode#4]
求问一下楼主如果在服务器上部署的话，nvim+PackerSync总是failed to update，有么有什么办法能离线部署呢？

**Comment by itsuki0927** [comment]
我周末尝试一下你说的这个

**Comment by itsuki0927** [comment]
我谷歌了一下看到了这个[帖子](https://www.reddit.com/r/vim/comments/bogy8g/how_can_i_install_vim_plugin_offline/), 你可以试试, 我感觉的话就是复制`/Users/用户名/.local/share/nvim`这个文件夹复制到服务器上, 还有就是vim配置复制过去, 我没有试过, 你可以试试哈.
