### ISSUE TITLE
你的目录压根就没有plugins啊，怎么添加插件？

### ISSUE THREAD

**Issue by scarin** [itsuki0927/SkCode#5]

**Comment by scarin** [comment]
> 

Spawning language server with cmd: `vscode-eslint-language-server` failed. The language server is either not installed, missing from PATH, or not executable.
Spawning language server with cmd: `typescript-language-server` failed. The language server is either not installed, missing from PATH, or not executable.
Spawning language server with cmd: `tailwindcss-language-server` failed. The language server is either not installed, missing from PATH, or not executable.

![image](https://user-images.githubusercontent.com/4132117/160114340-26e08bc0-ee2d-45e0-b669-558193642486.png)

打开js文件出现这个提示 - -b 没能找到解决方法，大神，这个怎么处理

**Comment by itsuki0927** [comment]
安装lsp服务`npm i -g vscode-langservers-extracted`. 可以看看[lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#html).

如果要装一个lsp:
1. 安装lsp服务, 也就是在[lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#html)中找到对应的lsp服务, 比如说`js`、`ts`是`tsserver`.
2. 在`plugin-configs/lsp/install.lua`中进行安装.
这样子才是正确安装一个lsp服务, 可以看看文档哈, 我文档中都有写.

(我本地还在重构lsp这一块, 这两天在好好弄一下)

**Comment by scarin** [comment]
> 

我try try

**Comment by itsuki0927** [comment]
所有lsp正常工作:

<img width="1310" alt="Screen Shot 2022-03-25 at 7 52 38 PM" src="https://user-images.githubusercontent.com/40518195/160116035-78f2dff8-be70-4fbc-ac12-7280298d591c.png">
这些都可以在lspconfig中找到.

格式化正常工作:
1. 前端**全局安装prettier**.
2. lua**全局安装stylua**.

当然你也可以自己去配置你的lsp服务啥(步骤就是我上面所说的), 这取决你自己啦.
