### ISSUE TITLE
安装完成后，缺少部分 language-server

### ISSUE THREAD

**Issue by JayeZhu** [itsuki0927/SkCode#6]
Spawning language server with cmd: `vscode-eslint-language-server` failed. The language server is either not installed, missing from PATH, or not executable.

**Comment by itsuki0927** [comment]
可以使用`npm i -g vscode-eslint-language-server`、`yarn global add vscode-eslint-language-server`.

- 使用tailwindcss 使用`npm install -g @tailwindcss/language-server`安装.
- 使用js、ts、tsx、jsx 使用`npm install -g typescript typescript-language-server`安装.
- 使用vue3 使用`npm install -g @volar/vue-language-server` 安装.
- 使用vue2 使用`npm install -g vls`安装.
- 使用css、json、html 使用`npm i -g vscode-eslint-language-server`安装.
- 使用emmet_ls 使用`npm install -g emmet-ls`安装.
- 使用eslint 使用`npm i -g eslint`安装.
- 使用markdown 查看[文档](https://github.com/artempyanykh/marksman)进行安装.
- 使用lua 查看[文档](https://github.com/sumneko/lua-language-server)进行安装.

**Comment by itsuki0927** [comment]
如果你想要格式化的话, 可以使用`npm i -g prettier`全局安装即可使用格式化.
