### ISSUE TITLE
LSP 的代码提示 icon 似乎有问题

### ISSUE THREAD

**Issue by legends-killer** [itsuki0927/SkCode#8]
如图，在使用了 [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons). 要求的字体后，文件目录能正常显示 icon，但是 LSP 的代码提示却仍会出现丢失的 icon，该如何解决呢？请赐教～
![image](https://user-images.githubusercontent.com/47050572/189484816-76feebb5-8e03-488d-a6bd-e3bfca88732b.png)

![image](https://user-images.githubusercontent.com/47050572/189491840-19bf2e89-583b-489c-a6fa-2dc667db2b1a.png)

**Comment by itsuki0927** [comment]
因为lsp的icon是使用的vscode的icon, 但是我们使用的字体中没有这些icon, 所以需要打一个补丁(把vscode的icon添加到你当前的字体中) ,所以需要以下几步:

1. 需要在这里下载vscode的[icon 字体](https://github.com/microsoft/vscode-codicons/releases/tag/0.0.32).
2. 解压出来之后dist文件下的 ttf文件, 把它放到桌面.
3. 需要一个font-patcher对当前字体打一个补丁, 具体步骤可以看[font-patcher](https://github.com/ryanoasis/nerd-fonts#font-patcher)

如果有报错的话, 可以查看这个[issue](https://github.com/ryanoasis/nerd-fonts/issues/225), 如果不是这个问题的话, 可以在[nred-font](https://github.com/ryanoasis/nerd-fonts/issues)这个仓库的issue搜索相关的问题, 会有答案的.

**Comment by legends-killer** [comment]
已解决，感谢~
